name: ci

on:
  push:
  pull_request:

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Repository verification
        shell: pwsh
        run: ./scripts/dev/Test-Repository.ps1
